config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # devise_for :headhunters
  # devise_for :users

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  devise_for :headhunters, controllers: {
    sessions: 'headhunters/sessions',
    passwords: 'headhunters/passwords',
    registrations: 'headhunters/registrations'
  }
  root to: 'pages#home'
  resources :jobs, only: [:new, :create, :index, :show, :edit, :update] do
    post :enroll
  end
  resources :profiles, only: [:new, :create, :edit, :show, :update] do
    post :bookmark
  end
  resources :comments
  resources :favorites, only: [:index]
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  has_many :comments
  has_many :headhunters, :through => :comments

  has_many :favorites
  has_many :headhunters, :through => :favorites

  def self.incomplete
    !where(name: [nil, '']).or(where(social_name: [nil, ''])).or(where(birth_date: [nil])).or(where(formation: [nil, ''])).or(where(description: [nil, ''])).or(where(experience: [nil, ''])).blank?
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :bookmark]
  before_action :authenticate_headhunter!, only: [:show, :bookmark]
  #before_action :check_profile_presence, only: [:new, :create]

  
  def new
    if Profile.where("user_id = ?", current_user.id).blank? 
      @profile = current_user.profiles.build
    else
      redirect_to edit_profile_path(current_user.id)
    end
  end

  def create
    @user = current_user
    @profile = @user.profiles.create(profile_params)
    if @profile.save
      :new
      redirect_to root_path
    end
  end

  def update
    @profile = current_user.profiles.find(params[:id])

    if @profile.update(profile_params)
      redirect_to root_path
    else
      render action: "edit"
    end
  end

  def edit
    @profile = current_user.profiles.find_by(user_id: current_user.id)
  end

  def show
    @profile = Profile.find_by(user_id: params[:id])
    @comments = @profile.comments.all
    @comment = @profile.comments.build
  end

  def bookmark
    if Favorite.exists?(profile_id: params[:profile_id], headhunter_id: params[:headhunter_id])
      flash[:alert] = "Esse perfil já está nos seus favoritos."
    else
      @favorite = Favorite.new(profile_id: params[:profile_id], headhunter_id: params[:headhunter_id])
      @favorite.save
      flash[:notice] = "Perfil incluído nos seus favoritos."
    end
    redirect_to request.referrer
  end

  private
    def profile_params
      params.require(:profile).permit(:name, :social_name, :birth_date, :formation, :description, :experience, :picture, :user_id)
    end
  
end

app/views/profiles/_form.html.erb
<div class="col-md-6 col-md-offset-3">
  <%= form_with(model: profile) do |f| %>
    <div class="card">
      <div class="card-body">
      
        <div class="mb-3">
          <%= f.label :name, 'Nome Completo', { class: "form-label"} %>
          <%= f.text_field :name, { class: "form-control"} %>
        </div>
        <div class="mb-3">
          <%= f.label :social_name, 'Nome Social', { class: "form-label"} %>
          <%= f.text_field :social_name, { class: "form-control"} %>
        </div>
        <div class="mb-3">
          <%= f.label :birth_date, 'Data de Nascimento', { class: "form-label"} %>
          <%= f.date_field :birth_date, { class: "form-control"} %>
        </div>
        <div class="mb-3">
          <%= f.label :formation, 'Formação', { class: "form-label"} %>
          <%= f.text_field :formation, { class: "form-control"} %>
        </div>
        <div class="mb-3">
          <%= f.label :description, 'Descrição', { class: "form-label"} %>
          <%= f.text_area :description, { class: "form-control"} %>
        </div>
        <div class="mb-3">
          <%= f.label :experience, 'Experiência', { class: "form-label"} %>
          <%= f.text_area :experience, { class: "form-control"} %>
        </div>

        <%= f.hidden_field :user_id %>

        <%= f.submit 'Salvar', class: "btn btn-default btn-primary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/profiles/edit.html.erb
<div class="container-fluid">
  <p class="h2">Editar Perfil</p>

  <%= render 'form', profile: @profile %>
</div>

app/views/profiles/new.html.erb
<div class="container-fluid">
  <p class="h2">Cadastrar Perfil</p>
  
  <%= render 'form', profile: @profile %>
</div>

app/views/profiles/show.html.erb
<div class="container-fluid">
  <p class="h2">Perfil do candidato</p>
  <div class="card">
    <div class="card-body">
      <h4 class="card-title" >
        <%= @profile.social_name %>
      </h4>
      <br>

      <div class="row">
        <label class="col-sm-2 col-label"><b>Nome:</b></label>
        
        <div class="col-sm-10">
          <%= @profile.name %>
        </div>
      </div>

      <div class="row">
        <label class="col-sm-2 col-label"><b>Nome Social:</b></label>
        
        <div class="col-sm-10">
          <%= @profile.social_name %>
        </div>
      </div>

      <div class="row">
        <label class="col-sm-2 col-label"><b>Data de Nascimento:</b></label>
        
        <div class="col-sm-10">
          <% unless @profile.birth_date.blank? %>
            <%= @profile.birth_date.strftime("%d/%m/%Y") %>
          <% end %>
        </div>
      </div>

      <div class="row">
        <label class="col-sm-2 col-label"><b>Formação:</b></label>
        
        <div class="col-sm-10">
          <%= @profile.formation %>
        </div>
      </div>

      <div class="row">
        <label class="col-sm-2 col-label"><b>Descrição:</b></label>
        
        <div class="col-sm-10">
          <%= @profile.description %>
        </div>
      </div>

      <div class="row">
        <label class="col-sm-2 col-label"><b>Experiência:</b></label>
        
        <div class="col-sm-10">
          <%= @profile.experience %>
        </div>
      </div>
      <br>

      <%= link_to 'Favoritar', profile_bookmark_path(@profile, headhunter_id: current_headhunter.id), method: :post, class: "btn btn-primary" %>
    </div>
    
    <hr class="w-100">
    
    <div class="container-fluid">
      <p class="h4">Comentários</p>

      <div class="col-md-10">
        <% @comments.each do |comment| %>
          <% if comment.headhunter_id == current_headhunter.id %>   
            <div class="md-3">
              <label class="text-muted">Data: <%= comment.updated_at.strftime("%d/%m/%Y %T") %> </label>
              <p><%= comment.body %></p>
              <p><%= link_to 'Deletar', comment_path(comment), method: :delete, data: { confirm: 'Tem certreza?' } %></p>
            </div>
          <% end %>
        <% end %>
        <%= render partial: 'comments/form', locals: { comment: @comment } %>
      </div>
    </div>

  </div>
</div>