config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # devise_for :headhunters
  # devise_for :users

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  devise_for :headhunters, controllers: {
    sessions: 'headhunters/sessions',
    passwords: 'headhunters/passwords',
    registrations: 'headhunters/registrations'
  }
  root to: 'pages#home'
  resources :jobs, only: [:new, :create, :index, :show, :edit, :update] do
    post :enroll
  end
  resources :profiles, only: [:new, :create, :edit, :show, :update] do
    post :bookmark
  end
  resources :comments
  resources :favorites, only: [:index]
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :headhunter
  accepts_nested_attributes_for :headhunter
  has_many :subscriptions
  has_many :users, through: :subscriptions
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_headhunter!, except: [:index, :show, :enroll]
  before_action :authenticate_user!, only: [:show, :enroll]

  def new
    @job = Job.new
  end

  def create
    @headhunter = current_headhunter
    @job = @headhunter.jobs.create(job_params)
    if @job.save
      :new
      redirect_to jobs_path
    end
  end

  def index
    @jobs = current_headhunter.jobs
  end

  def show
    @jobs = Job.find(params[:id])
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])

    if @job.update(job_params)
      redirect_to root_path
      flash[:notice] = "Vaga atualizada com sucesso."
    else
      render action: "edit"
    end
  end
  
  def enroll
    if Subscription.exists?(job_id: params[:job_id], user_id: params[:user_id])
      flash[:alert] = "Você já está inscrito para essa vaga."
    else
      @subscription = Subscription.new(job_id: params[:job_id], user_id: params[:user_id])
      @subscription.save
      flash[:notice] = "Inscrição realizada com sucesso."
    end
    redirect_to root_path
  end

  private
    def job_params
      params.require(:job).permit(:title, :description, :skills, :salary_range, :level, :deadline, :location, :closed)
    end
end

app/views/jobs/_form.html.erb
<div class="col-md-6 col-md-offset-3">
  <%= form_with(model: job) do |f| %>
    <div class="card">
      <div class="card-body">

        <div class="mb-3">
          <%= f.label :title, 'Título', { class: "form-label"} %>
          <%= f.text_field :title, { class: "form-control" } %>
        </div>
        
        <div class="mb-3">
          <%= f.label :description, 'Descrição', { class: "form-label"} %>
          <%= f.text_area :description, { class: "form-control" } %>
        </div>

        <div class="mb-3">
          <%= f.label :skills, 'Habilidades Desejadas', { class: "form-label"} %>
          <%= f.text_field :skills, { class: "form-control" } %>
        </div>

        <div class="mb-3">
          <%= f.label :salary_range, 'Faixa Salarial', { class: "form-label"} %>
          <%= f.text_field :salary_range, { class: "form-control" } %>
        </div class="mb-3">

        <div class="mb-3">
          <%= f.label :level, 'Nível', { class: "form-label"} %>
          <%= f.text_field :level, { class: "form-control" } %>
        </div>

        <div class="mb-3">
          <%= f.label :deadline, 'Data Limite', { class: "form-label"} %>
          <%= f.date_field :deadline, { class: "form-control" } %>
        </div>

        <div class="mb-3">
          <%= f.label :location, 'Localização', { class: "form-label"} %>
          <%= f.text_field :location, { class: "form-control" } %>
        </div>
        <% if !current_page?(new_job_path) %>
        <div class="mb-3">
          <%= f.check_box :closed %>
          <%= f.label :closed, 'Encerrada' %>
        </div>
        <% end %>

        <%= f.submit 'Salvar', class: "btn btn-default btn-primary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/jobs/edit.html.erb
<div class="container-fluid">
  <p class="h2">Editar Vaga</p>

  <%= render 'form', job: @job %>
</div>

app/views/jobs/index.html.erb
<div class="container-fluid">
  <p class="h2">Minhas Vagas</p>
  
  <% @jobs.each do |job| %>
    <div class="card">
      <div class="card-body">
        <label class="h4"><%= job.title %></label>
        <%= link_to 'Editar', edit_job_path(job) %>
        <p class="h6">Candidatos Inscritos</p>
          <%= render job.subscriptions %>
      </div>
    </div>
  <% end %>
    
    
</div>

app/views/jobs/new.html.erb
<h1>Cadastrar Nova Vaga</h1>

<%= form_with(model: Job.new) do |f| %>
  <div>
    <%= f.label :title, 'Título' %>
    <%= f.text_field :title %>
  </div>
  
  <div>
    <%= f.label :description, 'Descrição' %>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.label :skills, 'Habilidades Desejadas' %>
    <%= f.text_field :skills %>
  </div>

  <div>
    <%= f.label :salary_range, 'Faixa Salarial' %>
    <%= f.text_field :salary_range %>
  </div>

  <div>
    <%= f.label :level, 'Nível' %>
    <%= f.text_field :level %>
  </div>

  <div>
    <%= f.label :deadline, 'Data Limite' %>
    <%= f.text_field :deadline %>
  </div>

  <div>
    <%= f.label :location, 'Localização' %>
    <%= f.text_field :location %>
  </div>

  <%= f.submit 'Salvar' %>
<% end %>

app/views/jobs/show.html.erb
<div class="container-fluid">
  <p class="h2">Detalhes da Vaga</p>
  <div class="card">
    <div class="card-body">
      <h4 class="card-title">
        <%= @jobs.title %>
      </h4>
      <br>
      <div class="row">
        <label class="col-sm-2 col-label"><b>Descrição da Vaga:</b></label>
        
        <div class="col-sm-10">
          <%= @jobs.description %>
        </div>
      </div>

      <div class="row">
        <label class="col-sm-2 col-label"><b>Habilidades Desejadas:</b></label>
        
        <div class="col-sm-10">
          <%= @jobs.skills %>
        </div>
      </div>

      <div class="row">
        <label class="col-sm-2 col-label"><b>Nível:</b></label>
        
        <div class="col-sm-10">
          <%= @jobs.level %>
        </div>
      </div>

      <div class="row">
        <label class="col-sm-2 col-label"><b>Faixa Salarial:</b></label>
        
        <div class="col-sm-10">
          <%= @jobs.salary_range %>
        </div>
      </div>

      <div class="row">
        <label class="col-sm-2 col-label"><b>Localização:</b></label>
        
        <div class="col-sm-10">
          <%= @jobs.location %>
        </div>
      </div>

      <div class="row">
        <label class="col-sm-2 col-label"><b>Data Limite:</b></label>
        
        <div class="col-sm-10">
          <%= @jobs.deadline.strftime('%d/%m/%Y') %>
        </div>
      </div>
      <br>
      
      <%= link_to 'Increver-se', job_enroll_path(@jobs, user_id: current_user.id), method: :post, class: "btn btn-primary" %>
      <%= link_to 'Voltar', root_path, class: "btn btn-secondary" %>
    </div>
  </div>
</div>