config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # devise_for :headhunters
  # devise_for :users

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  devise_for :headhunters, controllers: {
    sessions: 'headhunters/sessions',
    passwords: 'headhunters/passwords',
    registrations: 'headhunters/registrations'
  }
  root to: 'pages#home'
  resources :jobs, only: [:new, :create, :index, :show, :edit, :update] do
    post :enroll
  end
  resources :profiles, only: [:new, :create, :edit, :show, :update] do
    post :bookmark
  end
  resources :comments
  resources :favorites, only: [:index]
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Dragon Mantis', root_path, class: "navbar-brand" %>
    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if headhunter_signed_in? %>
          <%= link_to 'Cadastrar Vaga', new_job_path, class: "nav-item nav-link" %>
          <%= link_to 'Meus Favoritos', favorites_path, class: "nav-item nav-link" %>
        <% end %>
        
        <% if user_signed_in? %>
          <%= link_to 'Perfil', new_profile_path, class: "nav-item nav-link" %>
          <%= link_to 'Comentários', comments_path, class: "nav-item nav-link" %>
        <% end %>
      </ul>
      
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <%= link_to current_user.email, edit_user_registration_path, class: "nav-item nav-link" %>
          <%= link_to "Sair", destroy_user_session_path, method: :delete, class: "nav-item nav-link" %>
        <% elsif headhunter_signed_in? %>
          <%= link_to current_headhunter.email, edit_headhunter_registration_path, class: "nav-item nav-link" %>
          <%= link_to "Sair", destroy_headhunter_session_path, method: :delete, class: "nav-item nav-link" %>
        <% else %>
          <span class="navbar-text border-md-right">
            Cadastre-se
          </span>
          
          <%= link_to "Candidato", new_user_registration_path, class: "nav-item nav-link", id: 'signup_candidate' %>
          <%= link_to "Headhunter", new_headhunter_registration_path, class: "nav-item nav-link", id: 'signup_headhunter' %>
          <div class="dropdown">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Login
              </a>
              <ul class="dropdown-menu dropdown-menu-dark dropdown-menu-end" aria-labelledby="navbarDarkDropdownMenuLink">
                <li><%= link_to "Candidato", new_user_session_path, class: "dropdown-item" %></li>
                <li><%= link_to "Headhunter", new_headhunter_session_path, class: "dropdown-item", id: 'login_headhunter' %></li>
              </ul>
            </li>
          </div>

        <% end %>        
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vagas de Empregos | Dragon Mantis</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    
    <%= render 'layouts/navbar' %>
    
    <div class='content'>
      <%= yield %>
    </div>
  </body>
</html>